<?php

namespace AppBundle\Repository;

/**
 * FruitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FruitRepository extends \Doctrine\ORM\EntityRepository
{
  //on ajoute ici nos méthodes personnalisées de récupération des données

  //Impossible de cibler une propriété .name puisque f.ctagory renvoie un tableau. Il faut trouver un moyen de cibler la propriété .name des objets de type category situés à l'intérieur du tableau f.category
  public function findByCategoryName($name) {
    $query =
    'SELECT f
     FROM AppBundle:Fruit f
     JOIN f.category c
     WHERE c.name = :name
     ';

    return $this->getEntityManager()
        ->createQuery($query)
        ->setParameter(':name', $name)
        ->getResult();
  }
  // public function findAllAssignedFruit($name) {
  //   return $this->getEntityManager()
  //     ->createQuery(
  //       'SELECT f
  //        FROM AppBundle:Fruit f
  //        WHERE EXISTS (SELECT c FROM AppBundle:Category c WHERE f = c.)
  //        ')
  //     ->getResult();
  // }

}
